### ISSUE TITLE
Server zibi.openstreetmap.org.pl fails for HTTPS

### ISSUE THREAD

**Issue by stoecker** [kendzi/Simple3dBuildingsPreset#2]
Hello,

the server responds to HTTPS, but not properly. See also
https://josm.openstreetmap.de/ticket/16123

Would be fine if this could be fixed and the preset completely use HTTPS.

**Comment by stoecker** [comment]
Also affects
 * TombPlugin.jar
 * jogl.jar
 * kendzi3d-resources.jar
 * kendzi3d.jar

**Comment by stoecker** [comment]
And it uses http-link for josm.openstreetmap.de and also www.w3.org (probably as XMLNS which can completely be dropped).

**Comment by kendzi** [comment]
Sorry to say, but is not my ftp server and I don't have any control over it. Owner kindly allow me to use it years ago to host my plugins. But since then I do not have any contact with him. But as it is private ftp server, I don't think owner will be instead in upgrading it especially if it involve paying for valid certificate. If that certificate is hard requirements I could try to contact him after Easter holidays, hopefully he don't turn off it compactly.

About http-links you referring about links inside preset?

**Comment by stoecker** [comment]
Yes. The links inside.

It is no hard requirement. Only a reminder. Many people aren't aware of broken setups and contacting them helped in many cases. Let's encrypt is free and when the owner has control over the server it can be setup easily. Please contact him and ask if he can fix it. But we wont drop any http links in the immediate future. :-)

P.S. If it is only for storing the plugins? Why don't you simply use GitHub like most of the others who develop the plugins on GitHub?

**Comment by kendzi** [comment]
Because when I start project GitHub didn't have hosting for released application versions. I know that some time ago it was added. But for "kendzi3d" I have setup deployment pipeline on my Jenkins and I simply left with it because i do not have time to setup new configuration.

**Comment by stoecker** [comment]
Any news?

If zibi can't hbe https, can you at least fix these two issues:

> And it uses http-link for josm.openstreetmap.de and also www.w3.org (probably as XMLNS which can completely be dropped).

**Comment by kendzi** [comment]
Sorry, i didn't have time and later forgot about it. I send email today.
About https I just look into defaultpresets.xml inside Josm and I see:
```
<presets xmlns="http://josm.openstreetmap.de/tagging-preset-1.0">
```
So looks like http link is still official :/

Links to wiki fixed in d6c9995604c600da70d93bc0e1f21630cb54fcd8

**Comment by stoecker** [comment]
> So looks like http link is still official :/

Yes. Changing the namespace will cause too much trouble, so we leave it. But the other link is gone, so the warnings will be silenced.

**Comment by kendzi** [comment]
That ftp finally died. I move file to github hosting. So solved :)
