### ISSUE TITLE
No file found for: http://zibi.openstreetmap.org.pl/kendzi/k/Simple3dPreset/s3db-preset.zip

### ISSUE THREAD

**Issue by don-vip** [kendzi/Simple3dBuildingsPreset#3]
See https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/lastCompletedBuild/jdk=JDK8/testReport/

**Comment by kendzi** [comment]
Moved to github so it should not cause troubles in future

**Comment by don-vip** [comment]
Thanks!
